### ISSUE TITLE
OnBehalfof

### ISSUE THREAD

**Issue by mascon** [jhoerr/box-csharp-sdk-v2#37]
Can you please add this feature ASAP

http://developers.blog.box.com/2013/03/08/announcing-on-behalf-of-the-simplest-most-powerful-admin-api-youll-ever-use/

**Comment by jhoerr** [comment]
On-Behalf-Of is supported as of eaf9992e58616f9229fc5c8cb2e172323b21f111.

Example usage:  

``` csharp
var folder = client.OnBehalfOf("user@domain.com").GetFolder("id");
```

A few notes:
- As with shared link URLs, this header is applied on a per-request basis.  So you'll need to use the fluent `client.OnBehalfOf(...)` syntax prior to each request.
- This feature is restricted by Box to enterprise admins with a particular OAuth access scope.  You'll need to talk to Box in order to enable this scope!
