### ISSUE TITLE
Collaboration Roles

### ISSUE THREAD

**Issue by mbricker** [jhoerr/box-csharp-sdk-v2#41]
Trying to set up a collaboration with roles of PreviewerUploader or ViewerUploader does not work. It turns out to be a bit of a problem in the Box SDK. Here is feedback straight from Box (we're an enterprise customer):

It works when you add the permissions exactly like this "previewer uploader" or "viewer uploader"

**Comment by jhoerr** [comment]
Thanks for catching that!  I was using [these values](https://support.box.com/entries/20366031-what-are-the-different-collaboration-permissions-and-what-access-do-they-provide) verbatim, with the dashes.  I'll get this fixed right quick.

**Comment by jhoerr** [comment]
Ok, I've fixed this in 88da9593792d35283e37a456925568fd97e32808. There's a wrinkle though.  Due to some impedance mismatches with Box's response formatting and Json.Net's de/serialization strategies, I had to move the property supplying the `CollaborationRole` enum from `Collaboration.Role` to `Collaboration.RoleValue`.  This is a breaking change, albeit a minor one.  Let me know how it works for you.
